#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_home:
  path: /
  controller: App\Presentation\Home\Controller\HomeController::index

app_item_list:
  path: /item/list
  controller: App\Presentation\Item\Controller\ManageItemController::showList

app_item_create:
  path: /item/create
  controller: App\Presentation\Item\Controller\ManageItemController::createItem

app_item_show:
  path: /item/{id}
  controller: App\Presentation\Item\Controller\ManageItemController::showItem

app_item_edit:
  path: /item/edit/{id}
  controller: App\Presentation\Item\Controller\ManageItemController::editItem

app_item_detail:
  path: /item/detail/{id}
  controller: App\Presentation\Item\Controller\ItemController::index

# -------- Promotion -----
app_promotion_create:
  path: /promotion/create/{id}
  controller: App\Presentation\Promotion\Controller\PromotionController::create

app_promotion_edit:
  path: /promotion/edit/{id}
  controller: App\Presentation\Promotion\Controller\PromotionController::edit

# -------- Cart Details -----
app_cart:
  path: /cart
  controller: App\Presentation\Order\Controller\CartController::index
