#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_home:
  path: /
  controller: App\Presentation\Home\Controller\HomeController::index

app_product_detail:
  path: /product/detail/{id}
  controller: App\Presentation\Product\Controller\ProductController::index

app_products_list:
  path: /product/list
  controller: App\Presentation\Product\Controller\ManageProductController::showList

app_product_create:
  path: /product/create
  controller: App\Presentation\Product\Controller\ManageProductController::create

app_product_view:
  path: /product/{id}
  controller: App\Presentation\Product\Controller\ManageProductController::view

app_product_edit:
  path: /product/edit/{id}
  controller: App\Presentation\Product\Controller\ManageProductController::edit

# -------- Promotion -----
app_promotion_create:
  path: /promotion/create/{id}
  controller: App\Presentation\Promotion\Controller\PromotionController::create

app_promotion_edit:
  path: /promotion/edit/{id}
  controller: App\Presentation\Promotion\Controller\PromotionController::edit

# -------- Cart Details -----
app_cart:
  path: /cart
  controller: App\Presentation\Order\Controller\CartController::index

app_invoice_view:
  path: /invoice/{id}
  controller: App\Presentation\Order\Controller\CheckoutController::index

